// Generated by CoffeeScript 1.8.0

/*
#===========================================================================================================



 .d8888b.  8888888  .d88888b.      .d8888b.  8888888888 8888888b.  888     888 8888888888 8888888b.
d88P  Y88b   888   d88P" "Y88b    d88P  Y88b 888        888   Y88b 888     888 888        888   Y88b
Y88b.        888   888     888    Y88b.      888        888    888 888     888 888        888    888
 "Y888b.     888   888     888     "Y888b.   8888888    888   d88P Y88b   d88P 8888888    888   d88P
    "Y88b.   888   888     888        "Y88b. 888        8888888P"   Y88b d88P  888        8888888P"
      "888   888   888     888          "888 888        888 T88b     Y88o88P   888        888 T88b
Y88b  d88P   888   Y88b. .d88P    Y88b  d88P 888        888  T88b     Y888P    888        888  T88b
 "Y8888P"  8888888  "Y88888P"      "Y8888P"  8888888888 888   T88b     Y8P     8888888888 888   T88b



#===========================================================================================================
 */

(function() {
  var SIO, TEMPLATES, TRM, alert, app, badge, client_count, debug, help, info, port, router, rpr, server, urge, warn, whisper;

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = 'ソバ/SERVER';

  info = TRM.get_logger('info', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  urge = TRM.get_logger('urge', badge);

  whisper = TRM.get_logger('whisper', badge);

  help = TRM.get_logger('help', badge);

  TEMPLATES = require('./TEMPLATES');

  app = (require('express'))();

  server = (require('http')).Server(app);

  SIO = (require('socket.io'))(server);

  port = 3000;

  client_count = 0;

  router = (require('socket.io-events'))();

  router.on('*', (function(_this) {
    return function(socket, P, next) {
      var message, name;
      name = P[0], message = P[1];
      help('event:', name, message != null ? message : './.');
      return next();
    };
  })(this));

  router.on('gimme-json', (function(_this) {
    return function(socket, P, next) {
      var client_id, name, value, _ref, _ref1;
      help('gimme-json');
      name = P[0];

      /* first form when used in a Socket.IO handler, second form when used in a router's handler: */
      client_id = (_ref = (_ref1 = socket.client) != null ? _ref1.id : void 0) != null ? _ref : socket.sock.client.id;
      value = {
        'foo': 42,
        'bar': true,
        'client-id': client_id
      };
      socket.emit('heres-json', value);
      return next();
    };
  })(this));

  SIO.use(router);

  SIO.on('connection', function(socket) {
    var client_id, greet;
    client_count += 1;
    urge("" + client_count + " clients connected");

    /* http://stackoverflow.com/a/24232050/256361 */
    client_id = socket.client.id;
    greet = function() {
      debug('©wB1Ef', "/: emitting greeting");
      SIO.emit('news', "welcome to our new user " + client_id);
      return socket.emit('news', "your client ID is " + client_id);
    };
    setTimeout(greet, 1500);
    socket.on('disconnect', function() {
      client_count -= 1;
      return warn("" + client_count + " clients connected");
    });
    return null;
  });

  app.get('/', (function(_this) {
    return function() {
      return function(request, response) {
        var headers;
        headers = {
          'Access-Control-Allow-Origin': '*',
          'Content-Type': 'text/html; charset=utf-8'
        };
        response.writeHead(200, headers);
        response.write(TEMPLATES.monitor());
        return response.end();
      };
    };
  })(this)());

  this.serve = function() {
    return server = server.listen(port, function() {
      var host, _ref;
      help("server process running on Node v" + process.versions['node']);
      _ref = server.address(), host = _ref.address, port = _ref.port;
      return help("SoBa ソバ Server listening to http://" + host + ":" + port);
    });
  };

  if (module.parent == null) {
    this.serve();
  }

}).call(this);
