// Generated by CoffeeScript 1.8.0
(function() {
  var TEACUP, TRM, name_, rpr;

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  TEACUP = require('coffeenode-teacup');

  for (name_ in TEACUP) {
    eval("" + name_ + " = TEACUP[ " + (rpr(name_)) + " ]");
  }

  this.monitor = function() {
    return render((function(_this) {
      return function() {
        DOCTYPE(5);
        return HTML(function() {
          HEAD(function() {
            META({
              charset: 'utf-8'
            });
            TITLE('SoBa ソバ Monitor');
            return LINK({
              rel: 'shortcut icon',
              href: '/public/favicon.ico?v6'
            });
          });
          return BODY(function() {
            SCRIPT({
              src: 'http://code.jquery.com/jquery-1.11.1.js'
            });
            SCRIPT({
              src: '/socket.io/socket.io.js'
            });
            H1("SoBa ソバ Monitor");
            DIV('#news');
            COFFEESCRIPT(function() {
              var log, socket;
              log = console.log.bind(console);
              socket = io();
              return socket.on('news', function(message) {
                ($('#news')).append(($('<div></div>')).text(message));
                return ($('html, body')).stop().animate({
                  scrollTop: ($('#bottom')).offset().top
                }, 2000);
              });
            });
            return DIV('#bottom');
          });
        });
      };
    })(this));
  };

}).call(this);
